instrumentation:
  root: .
  default-excludes: true
  embed-source: false
  variable: __coverage__
  compact: true
  preserve-comments: false
  complete-copy: false
  save-baseline: false
extensions:
  - .jsx
  - .js
reporting:
  reports:
    - text
    - html
  dir: ./coverage